---
- name: Installing packages
  hosts: webservers
  become: true

  tasks:
  - name: Installing packages
    yum: 
      name: ['git', 'mysql', 'tree', 'docker*', 'which', 'wget']
      state: installed

