---
- name: Uninstalling httpd
  hosts: webservers
  become: true

  tasks:
  - name: Stop httpd service
    service:
      name: httpd
      state: stopped

  - name: Unstall httpd package
    yum:
      name: httpd
      state: removed

